# Example manifest describing how source renders should be processed.
# Each entry under `renders` maps a source image to one or more variants.
# Variants reference aspect ratio presets defined in src.config.ASPECT_RATIO_PRESETS
# and can chain multiple operations such as cropping, resizing and grading.
renders:
  - source: lobby_daylight.jpg
    variants:
      - filename: lobby_daylight_dci4k.jpg
        operations:
          - type: resize
            preset: dci_4k
          - type: grade
            exposure: 0.05
            contrast: 1.05
            saturation: 1.02
      - filename: lobby_daylight_square.jpg
        operations:
          - type: resize
            preset: square_1080
          - type: grade
            exposure: 0.1
      - filename: lobby_daylight_hero.jpg
        operations:
          - type: crop
            preset: hero_21x9
            offset: [0, -0.2]  # Bias crop slightly upward
          - type: resize
            preset: dci_4k
          - type: grade
            temperature_shift: 15  # Warm the image slightly
            micro_contrast: 1.1    # Enhance local contrast
      - filename: lobby_daylight_clean.jpg
        directory: clean
        operations:
          - type: inpaint
            mask: masks/lobby_daylight_furniture.png
            blur_radius: 20
            feather_radius: 6
          - type: material_enhance
            clarity: 1.25
            micro_contrast: 1.3
            depth: 1.08
            sheen: 1.04
  - source: rooftop_evening.png
    variants:
      - filename: rooftop_evening_story.png
        operations:
          - type: crop
            preset: web_16x9
          - type: resize
            preset: vertical_story
          - type: grade
            exposure: -0.05
            saturation: 1.1
      - filename: rooftop_evening_ultrawide.png
        operations:
          - type: resize
            preset: ultrawide