# Example manifest describing how source renders should be processed.
# Each entry under `renders` maps a source image to one or more variants.
# Variants reference aspect ratio presets defined in src.config.ASPECT_RATIO_PRESETS
# and can chain multiple operations such as resizing and grading.
renders:
  - source: lobby_daylight.jpg
    variants:
      - filename: lobby_daylight_dci4k.jpg
        operations:
          - type: resize
            preset: dci_4k
          - type: grade
            exposure: 0.05
            contrast: 1.05
            saturation: 1.02
      - filename: lobby_daylight_square.jpg
        operations:
          - type: resize
            preset: square_1080
          - type: grade
            exposure: 0.1
  - source: rooftop_evening.png
    variants:
      - filename: rooftop_evening_story.png
        operations:
          - type: resize
            preset: vertical_story
          - type: grade
            exposure: -0.05
            saturation: 1.1
      - filename: rooftop_evening_ultrawide.png
        operations:
          - type: resize
            preset: ultrawide
